### ISSUE TITLE
URLs starting with slash are considered file:/// URLs

### ISSUE THREAD

**Issue by tanmayrajani** [danburzo/percollate#33]
When an `href` in the webpage starts with `/`, it stays as is and hence the PDF viewer considers it a File URL. It should probably prepend it with the domain.

![image](https://user-images.githubusercontent.com/8295888/46914398-95451780-cfba-11e8-86f6-69b25279d8dc.png)

**Comment by ramadis** [comment]
Hey @danburzo, Do you mind if I give you a hand with this issue?

**Comment by danburzo** [comment]
@ramadis sure thing, thanks! 

I had looked into this earlier, but I wonder if I had broke it in the meantime. It's my understanding that Readability should already convert relative links to their absolute counterpart, so it would be interesting to figure out why it doesn't. 

```js
dom.reconfigure({ url: url });
```
[reconfigure](https://github.com/jsdom/jsdom#reconfiguring-the-jsdom-with-reconfiguresettings) will set all the necessary DOM objects to use the original page's URL:

> Note that changing the jsdom's URL will impact all APIs that return the current document URL, such as window.location, document.URL, and document.documentURI, as well as resolution of relative URLs within the document, and the same-origin checks and referrer used while fetching subresources. It will not, however, perform a navigation to the contents of that URL; the contents of the DOM will remain unchanged, and no new instances of Window, Document, etc. will be created.

So before we fix the links manually, it would be great to look into why it doesn't already work.

**Comment by ramadis** [comment]
Oh, nice to know! Will check it out right now!

**Comment by ramadis** [comment]
@danburzo Apparently, setting the URL is not enough to trigger the relative paths transformation. This last solution adds a line that should fix this issue.

**Comment by danburzo** [comment]
Nice! I didn't have time to check, but maybe it also fixes images with relative __src__?

**Comment by danburzo** [comment]
I haven't merged the fix yet, and on my machine at least it seems URLs are formatted correctly (absolute URLs)... So I was curious if it's a system thing, or a npm dependency version thing.

**Comment by tanmayrajani** [comment]
I tried `0.2.10` in my Ubuntu machine and still getting `file:///` URLs. Looks like a system thing to me.

**Comment by danburzo** [comment]
I've just merged into `master` @ramadis's PR, can you check against it if you still get the broken URLs? If it still persists, maybe the installation process grabs a different patch version of `jsdom` (or one of its dependencies) which may have introduced the bug?

**Comment by tanmayrajani** [comment]
Tested with `0.2.11` and I'm afraid it's still the same behaviour. I tried with other websites too, same thing happens. Maybe someone who's watching the repo and is on non-mac OS should try this too just for confirmation?

**Comment by danburzo** [comment]
> Tested with 0.2.11 and I'm afraid it's still the same behaviour.

Sorry I wasn't clearer in the message, the change is not yet published on `npm`, only merged into the `master` branch of the repo. I can publish it if it's easier to test.

**Comment by tanmayrajani** [comment]
I tried in the checked-out repo, verified the presence of the commit from @ramadis, still same thing happens. :cry:

**Comment by danburzo** [comment]
Thanks for looking into it, back to the drawing board then!
